brew "bash"
brew "bat"
brew "curl"
brew "docker-clean"
brew "fd"
brew "pinentry"
brew "gnupg"
brew "gpgme"
brew "fzf"
brew "git"
brew "jq"
brew "tree"
brew "wget"
brew "zoxide"
brew "zplug"
brew "zsh"
brew "mas"
cask "amneziavpn"
cask "orbstack"
cask "wezterm"
cask "telegram"
cask "yandex-music"
cask "drawio"
cask "dbeaver-community"
cask "karabiner-elements"
cask "lens"
cask "zed"
cask "postman"
mas "Delete Apps", id: 1033808943
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
